project:
  type: website

website:
  title: "Joel Nitta"
  navbar:
    background: primary
    right:
      - href: publications.qmd
      - href: software.qmd
      - href: blog.qmd
      - href: talks.qmd
      - href: content/pdf/Nitta_CV.pdf
        text: "CV"

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: jnitta_theme.css
    toc: true
    comments:
      giscus:
        repo: joelnitta/joelnitta-home
        repo-id: R_kgDOGZGr3w
        category: Comments
        category-id: DIC_kwDOGZGr384B_-52
        mapping: pathname
        input-position: top
        theme: light
        language: en
    include-in-header: header.html

babelquarto:
  mainlanguage: 'en'
  languages: ['ja']
title-ja: ニッタ ジョエル
description-ja: ニッタ ジョエルのウエブサイト
author-ja: ニッタ ジョエル
lang: en
