project:
  type: website

website:
  title: "Joel Nitta"
  navbar:
    background: primary
    right: []

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: jnitta_theme.css
    toc: true
    include-in-header: header.html

babelquarto:
  languagecodes:
  - name: ja
    text: "日本語"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['ja']
title-ja: ニッタ ジョエル
description-ja: ニッタ ジョエルのウエブサイト
author-ja: ニッタ ジョエル
lang: en
