project:
  type: website

website:
  title: "Joel Nitta"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: software.qmd
        text: Software
      - href: blog.qmd
        text: Blog
      - href: talks.qmd
        text: Talks
      - href: content/pdf/Nitta_CV.pdf
        text: "CV"
      - href: https://www.ja.joelnitta.com
        text: "Japanese"

format:
  html:
    theme:
      light: cosmo
      dark: superhero
    css: jnitta_theme.css
    toc: true
    comments:
      giscus:
        repo: joelnitta/joelnitta-home
        repo-id: R_kgDOGZGr3w
        category: Comments
        category-id: DIC_kwDOGZGr384B_-52
        mapping: pathname
        reactions-enabled: false
        input-position: top
        theme: light
        language: en
    include-in-header: header.html
