project:
  type: website

website:
  title: "Joel Nitta"
  navbar:
    background: primary
    right:
      - href: publications.qmd
      - href: software.qmd
      - href: blog.qmd
      - href: talks.qmd
      - href: teaching.qmd

babelquarto:
  languagecodes:
  - name: ja
    text: "日本語"
  - name: en
    text: "English"
  mainlanguage: 'en'
  languages: ['ja']
title-ja: ニッタ ジョエル
description-ja: ニッタ ジョエルのウエブサイト
author-ja: ニッタ ジョエル
