website:
  navbar:
    right:
      - href: publications.qmd
      - href: software.qmd
      - href: blog.qmd
      - href: talks.qmd
      - href: teaching.qmd
      - href: content/pdf/Nitta_CV.pdf
        text: "CV"

format:
  html:
    comments:
      giscus:
        repo: joelnitta/joelnitta-home
        repo-id: R_kgDOGZGr3w
        category: Comments
        category-id: DIC_kwDOGZGr384B_-52
        mapping: pathname
        input-position: top
        theme: light
        reactions-enabled: false
        language: en
