website:
  navbar:
    right:
      - href: content/pdf/Nitta_CV.pdf
        text: "CV"

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: jnitta_theme.css
    toc: true
    comments:
      giscus:
        repo: joelnitta/joelnitta-home
        repo-id: R_kgDOGZGr3w
        category: Comments
        category-id: DIC_kwDOGZGr384B_-52
        mapping: pathname
        input-position: top
        theme: light
        language: en
        reactions-enabled: false
    include-in-header: header.html
