```{r}
#| label: setup-pkgs
#| include: false
library(distilltools)
library(RefManageR)
library(bib2df)
library(bibtex)
library(janitor)
library(lubridate)
library(glue)
library(tidyverse)

source(here::here("R/functions.R"))
```

```{r}
#| label: setup-refs
#| include: false
#| message: false
#| warning: false
#| echo: false

# Load bibliography
# Export from Zotero by selecting My References, Export, Better BibLatex
# on default settings
bib_path <- here::here("_bib/references.bib")
# - as list
mybib <- ReadBib(bib_path, check = FALSE)
# - as dataframe
mybib_df_raw <-
  suppressWarnings(
    suppressMessages(
      bib2df(bib_path)
    )
  )
# Load other metadata
mybib_meta <- read_csv(here::here("_bib/ref_metadata.csv")) %>%
  select(-title) %>%
  mutate(`file-pdf` = here::here(`file-pdf`))

# Check that all pdf files exist
check_pdfs(mybib_meta)

# Format dataframe version of bibliography
mybib_df <-
  mybib_df_raw %>%
  clean_names() %>%
  select(key = bibtexkey, date, doi, title, author, journaltitle) %>%
  mutate(
    date = parse_date_time(date, "ymd"),
    year = year(date)) %>%
  arrange(desc(year), key) %>%
  # add other metadata (github repo, dryad link, preprint, etc)
  left_join(mybib_meta, by = "key")

# Set RefManageR options
oldopts <- BibOptions(
  style = "text",
  bib.style = "authoryear", 
  no.print.fields = c("doi", "issn", "isbn", "url",
    "urldate", "eprint", "eprinttype"),
  max.names = 50,
  dashed = FALSE, 
  sorting = "ydnt")
```
