on:
  push:
    branches: ja-source
  pull_request:
    branches: ja-source
  # to be able to trigger a manual build
  workflow_dispatch:

name: Render and deploy Book

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      RENV_PATHS_ROOT: ~/Library/Application Support/renv
    steps:
      - uses: actions/checkout@v2
      
      - name: Install cURL Headers
        run: |
          sudo apt-get install libcurl4-openssl-dev

      - name: Cache packages
        uses: actions/cache@v1
        with:
          path: ${{ env.RENV_PATHS_ROOT }}
          key: ${{ runner.os }}-renv-${{ hashFiles('**/renv.lock') }}
          restore-keys: |
            ${{ runner.os }}-renv-
     
      - name: Restore packages
        shell: Rscript {0}
        run: |
          if (!requireNamespace("renv", quietly = TRUE)) install.packages("renv")
          renv::restore()

      - name: Install Quarto
        uses: quarto-dev/quarto-actions/install-quarto@v1
        with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.105

      # Install any computing dependency you may need, usually either python and Jupyter or R
      # More specific examples will be shared on quarto-dev/quarto-actions project

      - name: Render book to all format
        # Add any command line argument needed
        run: |
          quarto render

      - name: Deploy 🚀
        # only deploy when push to main
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          # The branch the action should deploy to.
          branch: ja
          # The folder the action should deploy. Adapt if you changed in Quarto config
          folder: _site